package raiti.AutomaticQED;

import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import raiti.AutomaticQED.server.CommonProxy;

/**
 * オートマティックQED MOD メインクラス
 * <br>Created by Raiti-chan on 2016/12/07.
 *
 * @author Raiti-chan
 * @version 1.0.0 alpha
 * @since 1.0.0 alpha
 */
@SuppressWarnings({"WeakerAccess", "unused"})
@Mod(modid = AutomaticQED.MOD_ID, name = AutomaticQED.MOD_NAME, version = AutomaticQED.MOD_VERSION, useMetadata = true)
public class AutomaticQED {
	
	/**
	 * MODID
	 */
	public static final String MOD_ID = "AutomaticQED";
	/**
	 * MOD名
	 */
	public static final String MOD_NAME = "AutomaticQED";
	/**
	 * MODVersion
	 */
	public static final String MOD_VERSION = "1.0.0 alpha";
	/**
	 * Mod info
	 */
	@Mod.Metadata
	private static ModMetadata metadata;
	
	/**
	 * Mod Instance
	 */
	@Mod.Instance
	public static AutomaticQED instance;
	
	/**
	 * プロキシ―クラス
	 */
	@SidedProxy(serverSide = "raiti.AutomaticQED.server.CommonProxy", clientSide = "raiti.AutomaticQED.client.ClientProxy")
	public static CommonProxy proxy;
	
	
	/**
	 * PreInit
	 *
	 * @param event ForgeModLoaderイベント
	 */
	@EventHandler
	public void preinit(FMLPreInitializationEvent event) {
		this.loadMeta(metadata);
	}
	
	/**
	 * Init
	 *
	 * @param event ForgeModLoaderイベント
	 */
	@EventHandler
	public void init(FMLInitializationEvent event) {
		
	}
	
	/**
	 * PostInit
	 *
	 * @param event ForgeModLoaderイベント
	 */
	@EventHandler
	public void postinit(FMLPostInitializationEvent event) {
		
	}
	
	/**
	 * メタデータの書き込み
	 *
	 * @param modMetadata メタデータインスタンス
	 */
	private void loadMeta(ModMetadata modMetadata) {
		modMetadata.modId = MOD_ID;
		modMetadata.name = MOD_NAME;
		modMetadata.version = MOD_VERSION;
		modMetadata.authorList.add("Raiti-chan");
		modMetadata.description = "This Mod is ExtraUtilities's Add-on.\nAdding AutomaticQED and compressed Ender-Flux Crystal.";
		modMetadata.autogenerated = false;
	}
	
}
